import os

__author__ = 'jon'

SECRET_KEY = ""

basedir = os.path.abspath(os.path.dirname(__file__))

USERNAME = ""
PASSWORD = ""
LOCATION = ""
DATABASE = ""

SQLALCHEMY_DATABASE_URI = "mysql+pymysql://" + USERNAME + ":" + PASSWORD + "@" + LOCATION + "/" + DATABASE
SQLALCHEMY_MIGRATE_REPO = os.path.join(basedir, "db_repository")

SITE_ADMIN_USERNAME = ""
SITE_ADMIN_PASSWORD = ""
SITE_ADMIN_EMAIL = ""

HPC_JOB_SUBMISSION_FILE = ""

PIPELINES_PATH_ON_WEBSERVER = ""
PIPELINES_PATH_ON_HPC = ""

RAW_DATA_PATH_ON_WEBSERVER = ""
RAW_DATA_PATH_ON_HPC = ""

SUBMISSIONS_PATH_ON_WEBSERVER = ""
SUBMISSIONS_PATH_ON_HPC = ""

SAMPLES_PATH_ON_WEBSERVER = ""
SAMPLES_PATH_ON_HPC = ""

INVESTIGATIONS_PATH_ON_WEBSERVER = ""
INVESTIGATIONS_PATH_ON_HPC = ""
