#!/usr/bin/python

import cgi

link = cgi.FieldStorage()

CH = open("../template/cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("../template/template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("../template/template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

for ch in cgiHeader:
    print
    ch[:-1]

for he in topLines:
    print
    he[:-1]

masterProjectID = link["masterProjectID"].value

# Get the master project ID
from API.runQuery import runQuery

DBquery = "delete  from masterProject  where masterProjectID like " + masterProjectID

res = runQuery(DBquery)

# send it back to the projects page
print
'<script language="javascript" type="text/javascript">'
print
'window.location.href="/cgi-bin/projects?backurl="+window.location.href;'
print
'</script>'

for fo in bottomLines:
    print
    fo[:-1]
