#!/usr/bin/python


import cgi

form = cgi.FieldStorage()

CH = open("../template/cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("../template/template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("../template/template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

# from API.masterProject import masterProject
from API.runQuery import runQuery

for ch in cgiHeader:
    print
    ch[:-1]
for he in topLines:
    print
    he[:-1]

from API.runQuery import runQuery

masterProjectID = ""
seqLinks = []
analLinks = []
flowCytLinks = []

for t in form.keys():
    # print "<p>",t,form[t].value,"</p>"
    bits = t.split("_")
    if bits[0] == "seq":
        DBquery = "insert into typeLinker (parentID, childID, type) values ('" + bits[2] + "','" + bits[
            1] + "','sequencing')"
        res = runQuery(DBquery)
        masterProjectID = bits[2]

print
'<script language="javascript" type="text/javascript">'
print
'window.location.href="/cgi-bin/getProjectFromDB?projID=' + masterProjectID + '&backurl="+window.location.href;'
print
'</script>'

for fo in bottomLines:
    print
    fo[:-1]
