#!/usr/bin/python

import cgi

link = cgi.FieldStorage()

CH = open("../template/cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("../template/template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("../template/template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

from API.masterProject import masterProject

for ch in cgiHeader:
    print
    ch[:-1]

for he in topLines:
    print
    he[:-1]

if link.has_key('masterProjID'):
    masterProjID = link["masterProjID"].value

if link.has_key('documentID'):
    documentID = link["documentID"].value

i = masterProject()
i.getMasterProjectByID(masterProjID)
i.checkDocuments()

for docs in range(0, len(i.documents)):
    print
    "<p>A", i.documents[docs][0], documentID, "</p>"
    print
    "<p>B", int(i.documents[docs][0]), int(documentID), "</p>"

    if int(i.documents[docs][0]) == int(documentID):
        print
        "<p>HA</p>"
        i.removeDocumentByID(documentID)


# send it back to the project page

print
'<script language="javascript" type="text/javascript">'
print
'window.location.href="/cgi-bin/getProjectFromDB?projID=' + masterProjID + '";'
print
'</script>'

for fo in bottomLines:
    print
    fo[:-1]
