#!/usr/bin/python

import cgi

link = cgi.FieldStorage()

CH = open("../template/cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("../template/template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("../template/template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

from API.seqRun import seqRun

for ch in cgiHeader:
    print
    ch[:-1]

for he in topLines:
    print
    he[:-1]

seqProjectID = link["seqProjectID"].value

# Get the master project ID
from API.runQuery import runQuery

DBquery = "select masterProjectID from seqProject where seqProjectID like " + seqProjectID

masterProjectIDres = runQuery(DBquery)
masterProjectID = masterProjectIDres[0][0]
# print "<p>",masterProjectID,"</p>"
# print "<p>",masterProjectID[0],"</p>"
# print "<p>",masterProjectID[0][0],"</p>"

DBquery = "UPDATE masterProject SET localProjectID='NULL' where masterProjectID=" + str(masterProjectID)
res = runQuery(DBquery)

# DBquery="UPDATE masterProject SET projectType='NULL' where masterProjectID="+str(masterProjectID)
# res=runQuery(DBquery)


i = seqRun()
i.addSeqProject()
i.seqProjs[0].getSeqProjByID(seqProjectID)
i.seqProjs[0].deleteSeqProjectTree()

# Find out if this seqProject is mapped to any


print
"<p>seq project deleted</p>"

for fo in bottomLines:
    print
    fo[:-1]
