#!/usr/bin/python

import cgi

link = cgi.FieldStorage()

CH = open("../template/cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("../template/template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("../template/template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

from API.seqRun import seqRun

for ch in cgiHeader:
    print
    ch[:-1]

for he in topLines:
    print
    he[:-1]

sampleID = link["sampleID"].value

i = seqRun()
i.addSeqProject()
i.seqProjs[0].addLaneData()
i.seqProjs[0].lanes[0].addSamples()
i.seqProjs[0].lanes[0].samples[0].getSampleDataByID(sampleID)
i.seqProjs[0].lanes[0].samples[0].deleteSample()

print
"<p>Sample deleted</p>"

for fo in bottomLines:
    print
    fo[:-1]
