#!/usr/bin/python

import cgi

link = cgi.FieldStorage()

CH = open("../template/cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("../template/template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("../template/template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

for ch in cgiHeader:
    print
    ch[:-1]

for he in topLines:
    print
    he[:-1]

from PL_CONTROL.sftpTransfer import sftpTransfer

ST = sftpTransfer()
if link.has_key('seqProjectID'):
    ST.seqProjectID = int(link['seqProjectID'].value)

if link.has_key('username'):
    ST.username = link['username'].value


# print "<p>"+str(ST.seqProjectID)+"</p><p>"+ST.username+"</p><p>"+ST.transLocation+"</p>"

ST.loadSftpByUsername()
ST.resetPassword()
ST.setTransLocation()

print
"<p>Password generated. Password= <b>" + ST.password + "</b>.</p>"
print
"<p>Please take note of this password</p>"

print
'<p><a href="/cgi-bin/seqProjDetails?projID=' + str(
    ST.seqProjectID) + '">Return to sequencing project details page</a></p>'

print
"<hr><p>"
print
"<h4>Download Instructions</h4>"
print
"Username: " + ST.username + "<br>"
print
"Password: " + ST.password + "<br>"

print
"<p>The sftp server is: sheba.genetics.kcl.ac.uk</p>"

print
"<p>The server must be accessed via port 51515 (everything else is firewalled) so you should either set your client program to use port 51515 or if using the command line you could use the following example:<br>"
print
"sftp -o port=51515 " + ST.username + "@sheba.genetics.kcl.ac.uk</p>"
print
"<p>You can also use scp, so for example to get everything from this project in one go:<br>"
print
"scp -r -o port=51515 " + ST.username + "@sheba.genetics.kcl.ac.uk:/data/" + ST.seqRunName + " ./.</p>"
print
"<br><br>"



# print '<script language="javascript" type="text/javascript">'
# print 'window.location.href="/cgi-bin/seqProjDetails?projID='+str(ST.seqProjectID)+'";'
# print '</script>'


for fo in bottomLines:
    print
    fo[:-1]
