#!/usr/bin/python

import cgi

link = cgi.FieldStorage()

CH = open("../template/cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("../template/template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("../template/template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

for ch in cgiHeader:
    print
    ch[:-1]

for he in topLines:
    print
    he[:-1]

masterProjID = link["projectID"].value
seqProjs = []

for t in link.keys():
    # print "<p>",t,"</p>"
    if t[:4] == "link":
        seqProjs.append(link[t].value)

# print "<p>",seqProjs,masterProjID,"</p>"

from API.masterProject import masterProject

i = masterProject()
i.getMasterProjectByID(masterProjID)

from API.runQuery import runQuery

DBquery = "delete from seqProject where masterProjectID=" + str(i.masterProjectID)
res = runQuery(DBquery)

i.addSeqProject()
i.seqProjs[-1].getSeqProjByID(seqProjs[0])
i.seqProjs[-1].masterProjectID = masterProjID
i.seqProjs[-1].updateDB()

i.localProjectID = i.seqProjs[-1].seqProjectID
i.updateDB()

for fo in bottomLines:
    print
    fo[:-1]
