#!/usr/bin/python


import cgi

CH = open("../template/cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("../template/template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("../template/template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

for ch in cgiHeader:
    print
    ch[:-1]

for he in topLines:
    print
    he[:-1]

print
"<p>Upload csv file:</p>"
print
'<form name="input" enctype="multipart/form-data" action="/cgi-bin/upLoaderStage1" method="post">'
print
'<p><input type="file" name="seqDataFile" size="40"><br> <input type="submit" Value="Upload" ></p>'
print
'</form>'
"""
print "<p>or</p>"
print '<form name="pasteinput" action="/cgi-bin/upLoaderStage1" method="post">'
print "<p>Paste csv file here:</p>"
print '<textarea name="csv" width="400" height="50" > </textarea>'
print '<p><input type="submit" Value="Upload" ></p>'
print '</form>'
"""

print
"<hr>"
print
"<h2>Upload File Format</h2>"
print
"<p>CSV files can contain the following column headings:</p>"
print
"<table style='background-color:lightblue;' >"
print
'<tr><th align="left">Well</th><td>Currently unused.</td></tr>'
print
"<tr><th align='left'>Customer Sample ID</th><td>Sample name</td></tr>"
print
"<tr><th align='left'>P.I.</th><td>This becomes the sequencing project title</td></tr>"
print
"<tr><th align='left'>Project Title</th><td></td></tr>"
print
"<tr><th align='left'>Index kit I.D.</th><td>Options are: Illumina, Agilent SureSelect_XT</td></tr>"
print
"<tr><th align='left'>Index ID</th><td>The index number corresponding to the barcode sequence for the given kit</td></tr>"
print
"<tr><th align='left'>Pool I.D.</th><td>Currently unused.</td></tr>"
print
"<tr><th align='left'>Hi-Seq/Flow Cell Project number</th><td>The becomes the sequence experiment name.</td></tr>"
print
"<tr><th align='left'>Library Prep Operator</th><td>Currently unused.</td></tr>"
print
"<tr><th align='left'>Library Prep Start Date</th><td>Currently unused.</td></tr>"
print
"<tr><th align='left'>Library Prep End Date</th><td>Currently unused.</td></tr>"
print
"<tr><th align='left'>Samples sent for Sequencing</th><td>Currently unused.</td></tr>"
print
"<tr><th align='left'>Sequencing Start Date</th><td></td></tr>"
print
"<tr><th align='left'>Sequencing End Date</th><td></td></tr>"
print
"<tr><th align='left'>Sequencing Operator</th><td></td></tr>"
print
"<tr><th align='left'>Lane</th><td></td></tr>"
print
"<tr><th align='left'>Flow Cell I.D.</th><td></td></tr>"
print
"<tr><th align='left'># of Index Tag Cycles</th><td></td></tr>"
print
"<tr><th align='left'># of Read Cycles</th><td></td></tr>"
print
"<tr><th align='left'>Sequencing Concentration</th><td>Units are assumed to be pM</td></tr>"
print
"<tr><th align='left'>Index sequence</th><td></td></tr>"
print
"</table>"

print
"<p>The following columns are mandatory:</p>"
print
"<ul>"
print
"<li>Flow Cell I.D.</li>"
print
"<li>P.I.</li>"
print
"<li>Lane</li>"
print
"<li>Customer Sample ID</li>"
print
"</ul></p>"

print
"<p>The column order isn't important, however the column headings are case sensitive and must appear exactly as in the example.</p>"
print
"<p>An example csv file can be found <a href='/seqExample.csv'>here.</a></p><br>"

for fo in bottomLines:
    print
    fo[:-1]
