#!/usr/bin/python


import cgi
link = cgi.FieldStorage()


CH=open("./cgi_header","r")
cgiHeader=CH.readlines()
CH.close()

HF=open("./template_top","r")
topLines=HF.readlines()
HF.close()

FF=open("./template_bottom","r")
bottomLines=FF.readlines()
FF.close()

from API.runQuery import runQuery
from API.getExptByID import getExptByID
from API.getSeqProjByID import getSeqProjByID

for ch in cgiHeader:
        print ch[:-1]
for he in topLines:
	print he[:-1]


iD = link["exptID"].value
#iD="P211"

i=getExptByID(iD)
#Get unlinked seq projects

sPs=link.keys()
print "<p>",link.keys(),"</p>"

for li in range(0,len(sPs)):
	if sPs[li][:3]=="seq":
		print "<p>",sPs[li],link[sPs[li]],"</p>"
		IDsp=sPs[li].split("_")
		
		i.addSeqProject()
		i.seqProjs[-1].getSeqProjByID(IDsp[1])
		i.seqProjs[-1].seqExptID=iD
		i.seqProjs[-1].updateDB()


		#Get the IDs of all of the lanes in this project
		laneDataIDs=i.seqProjs[-1].getLaneDataIDs()

		i.seqProjs[-1].addLaneData()
		i.seqProjs[-1].updateDB()
		"""
		#Work down to the lane layer
		for la in range(0,len(laneDataIDs)):
			#add a lane instance
			if la>0 or len(i.seqProjs[-1eqProjs[-1].lanes)==0:
				if i.seqProjs[-1].lanes[-1].laneID!="NULL":
                              		i.seqProjs[-1].addLaneData()

			i.seqProjs[-1].lanes[-1].getLaneDataByID(laneDataIDs[la][0])

			sampleIDs=i.seqProjs[-1].lanes[-1].getSampleIDs()
			#print sampleIDs
			i.seqProjs[-1].lanes[-1].addSamples()	
			#Now we move into the sample layer
			for sa in range(0,len(sampleIDs)):
				#add a sample instance
				if sa>0 or len(i.seqProjs[-1].lanes[-1].samples)==0:
					if i.seqProjs[-1].lanes[-1].samples[-1].sampleID!=0:
                                              	i.seqProjs[-1].lanes[-1].addSamples()

				i.seqProjs[-1].lanes[-1].samples[-1].getSampleDataByID(sampleIDs[sa][0])
		"""






for fo in bottomLines:
	print fo[:-1]




