#!/usr/bin/python

import cgi
link = cgi.FieldStorage()




CH=open("./cgi_header","r")
cgiHeader=CH.readlines()
CH.close()


HF=open("./template_top","r")
topLines=HF.readlines()
HF.close()

FF=open("./template_bottom","r")
bottomLines=FF.readlines()
FF.close()

from API.seqExpt import seqExpt


for ch in cgiHeader:
        print ch[:-1]

for he in topLines:
	print he[:-1]



sampleID=link["sampleID"].value

i=seqExpt()
i.addSeqProject()
i.seqProjs[0].addLaneData()
i.seqProjs[0].lanes[0].addSamples()
i.seqProjs[0].lanes[0].samples[0].getSampleDataByID(sampleID)
i.seqProjs[0].lanes[0].samples[0].deleteSample()



print "<p>Sample deleted</p>"






for fo in bottomLines:
	print fo[:-1]




