#!/usr/bin/python


import cgi
link = cgi.FieldStorage()


CH=open("./cgi_header","r")
cgiHeader=CH.readlines()
CH.close()

HF=open("./template_top","r")
topLines=HF.readlines()
HF.close()

FF=open("./template_bottom","r")
bottomLines=FF.readlines()
FF.close()

from API.masterProject import masterProject
from API.getState import getState


for ch in cgiHeader:
        print ch[:-1]
for he in topLines:
	print he[:-1]

if link.has_key('type'):
	itemType = link["type"].value

if link.has_key('itemID'):
	itemID=link["itemID"].value


print "<h2>Project status</h2>"
status=getState(itemType, itemID)
print "<p> <img src='/CoreInSys/images/status_"+status+".gif' alt='status_"+status+"' > - "+status+"</p>"


print '<form name="stateForm" action="/cgi-bin/coreInSys/changeStatus" method="post">'

print "<input type='hidden' name='projectID' value='"+itemID+"'>"
print "<input type='hidden' name='type' value='"+itemType+"'>"

print "<p>Change status<br>"
if status!="RED":
	print "<input type='radio' name='state' value='RED'><img src='/CoreInSys/images/status_RED.gif'><br>"
if status!="AMBER":
        print "<input type='radio' name='state' value='AMBER'><img src='/CoreInSys/images/status_AMBER.gif'><br>"
if status!="BLUE":
	print "<input type='radio' name='state' value='BLUE'><img src='/CoreInSys/images/status_BLUE.gif'><br>"
if status!="GREEN":
	print "<input type='radio' name='state' value='GREEN'><img src='/CoreInSys/images/status_GREEN.gif'><br>"
print '<input type="submit" value="change status" >'

print "</form>"


print "</p>"



print "<hr>"
print "<ul>"
print "<li><img src='/CoreInSys/images/status_RED.gif'> - User intevention required.</li>"
print "<li><img src='/CoreInSys/images/status_BLUE.gif'> - Project running.</li>"
print "<li><img src='/CoreInSys/images/status_GREEN.gif'> - Project complete.</li>"
print "<li><img src='/CoreInSys/images/status_AMBER.gif'> - User inspection required.</li>"
print "</ul>"










for fo in bottomLines:
	print fo[:-1]




