#!/usr/bin/python


import cgi
form = cgi.FieldStorage()


CH=open("./cgi_header","r")
cgiHeader=CH.readlines()
CH.close()

HF=open("./template_top","r")
topLines=HF.readlines()
HF.close()

FF=open("./template_bottom","r")
bottomLines=FF.readlines()
FF.close()

from API.masterProject import masterProject



for ch in cgiHeader:
        print ch[:-1]
for he in topLines:
	print he[:-1]


if form.has_key('masterProjectID'):
	projectID=form["masterProjectID"].value

i=masterProject()
i.getMasterProjectByID(projectID)
customer=""
if form.has_key('projectName'):
	i.projectName=form["projectName"].value
if form.has_key('projectLead'):
        i.projectLead=form["projectLead"].value
if form.has_key('customer'):
        customer=form["customer"].value
if form.has_key('openDate'):
        i.openDate=form["openDate"].value
if form.has_key('lastUpdate'):
        i.lastUpdate=form["lastUpdate"].value
if form.has_key('projectLead'):
        i.projectLead=form["projectLead"].value
if form.has_key('status'):
        i.status=form["status"].value
if form.has_key('description'):
        i.description=form["description"].value

i.updateDB()



print '<table  border="1" align="center" valign="top" cellpadding="0" cellspacing="0" width=100%>'
print '<tr><th>Project Name</th><th>Project Lead</th><th>Customer ID</th><th>Project opened</th><th>Project last updated</th><th>Project Status</th></tr>'


print '<tr><td><a href="/cgi-bin/coreInSys/getProjectFromDB.cgi?projName='+i.projectName+'&projID='+i.masterProjectID+'"> '+i.projectName+'</a></td><td>'+i.projectLead+'</td><td>Customer</td><td>'+str(i.openDate)+'</td><td>'+str(i.lastUpdate)+'</td><td>'+i.status+'</td></tr>'
print '<tr><td colspan=7><p><br>'+i.description+'</p></td></tr>'
print '<tr><td colspan=7><a href="/cgi-bin/coreInSys/editMasterProject?projID='+i.masterProjectID+'">Edit Master Project Details</a></td></tr>'
print '<tr><td colspan=7><a href="/cgi-bin/coreInSys/createMasterProjectLink?projID='+i.masterProjectID+'">Create Master Project Link</a></td></tr>'

print '<tr>'
print "</table>"


print '<script language="javascript" type="text/javascript">'
print 'window.location.href="/cgi-bin/coreInSys/getProjectFromDB.cgi?projID='+projectID+'";'
print '</script>'






for fo in bottomLines:
	print fo[:-1]




