#!/usr/bin/python


import cgi
link = cgi.FieldStorage()


CH=open("./cgi_header","r")
cgiHeader=CH.readlines()
CH.close()

HF=open("./template_top","r")
topLines=HF.readlines()
HF.close()

FF=open("./template_bottom","r")
bottomLines=FF.readlines()
FF.close()

from API.getSeqProjByID import getSeqProjByID
from API.getExptByID import getExptByID



for ch in cgiHeader:
        print ch[:-1]




for he in topLines:
	print he[:-1]

#projectType=link["projType"].value


projectName = link["projName"].value

projectID=link["projID"].value


#i=getProjByID(projectID,"sequencing")
i=getSeqProjByID(0,projectID)
#print i.seqProjs[0].seqExptID
if 1:
	#get experimental details

	j=getExptByID(i.seqExptID)

	#print "<p>",j.flowcellID,"</p>"
	#print "<p>",j.dataLocation,"</p>"
	#print "<p>",j.indexTagCycles,"</p>"
	#print "<p>",j.readCycles,"</p>"

	from PL_CONTROL.demux import demux
	dm=demux(i,j)

	if link.has_key('--use-bases-mask'):
		dm.params['--use-bases-mask']=link['--use-bases-mask'].value

	if link.has_key('--input-dir'):
                dm.params['--input-dir']=link['--input-dir'].value

	if link.has_key('--intensities-dir'):
                dm.params['--intensities-dir']=link['--intensities-dir'].value

	if link.has_key('--positions-dir'):
                dm.params['--positions-dir']=link['--positions-dir'].value

	if link.has_key('--output-dir'):
                dm.params['--output-dir']=link['--output-dir'].value

	if link.has_key('--fastq-cluster-count'):
                dm.params['--fastq-cluster-count']=link['--fastq-cluster-count'].value

	if link.has_key('--flowcell-id'):
                dm.params['--flowcell-id']=link['--flowcell-id'].value

	if link.has_key('--tiles'):
                dm.params['--tiles']=link['--tiles'].value

	if link.has_key('--sample-sheet'):
                dm.params['--sample-sheet']=link['--sample-sheet'].value
	#options
	if link.has_key('--no-eamss'):
                dm.options['--no-eamss']=link['--no-eamss'].value

	if link.has_key('--force'):
                dm.options['--force']=link['--force'].value

	if link.has_key('--ignore-missing-stats'):
                dm.options['--ignore-missing-stats']=link['--ignore-missing-stats'].value

	if link.has_key('--ignore-missing-bcl'):
                dm.options['--ignore-missing-bcl']=link['--ignore-missing-bcl'].value

	if link.has_key('--ignore-missing-control'):
                dm.options['--ignore-missing-control']=link['--ignore-missing-control'].value



	#print "<p>Make sampleSheet</p>"
	dm.writeCommandFile()
	dm.makeSampleSheet()
	#print "<p>Demux bit.</p>"	
	dm.queueDemuxJob()
	#print "<p>Job queued?</p>"
	dm.insertDB()
	dm.getDemuxStatus()

	
	#send it back to the projects page
	"""	
	print '<script language="javascript" type="text/javascript">'
	print 'window.location.href="/cgi-bin/coreInSys/projects?backurl="+window.location.href;'
	print '</script>'
	"""

for fo in bottomLines:
	print fo[:-1]




