"""empty message

Revision ID: 26d219dee350
Revises: 4f19ac02204d
Create Date: 2016-05-20 13:35:15.779527

"""

# revision identifiers, used by Alembic.
revision = '26d219dee350'
down_revision = '4f19ac02204d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PipelineInstance', sa.Column('data_consignor_data_group_id', sa.Integer(), nullable=True))
    op.drop_constraint('PipelineInstance_ibfk_8', 'PipelineInstance', type_='foreignkey')
    op.create_foreign_key(None, 'PipelineInstance', 'DataGroup', ['data_consignor_data_group_id'], ['id'])
    op.drop_column('PipelineInstance', 'client_data_group_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PipelineInstance', sa.Column('client_data_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'PipelineInstance', type_='foreignkey')
    op.create_foreign_key('PipelineInstance_ibfk_8', 'PipelineInstance', 'DataGroup', ['client_data_group_id'], ['id'])
    op.drop_column('PipelineInstance', 'data_consignor_data_group_id')
    ### end Alembic commands ###
