"""empty message

Revision ID: 2b6fd9c6b493
Revises: 26d219dee350
Create Date: 2016-06-27 15:47:36.729261

"""

# revision identifiers, used by Alembic.
revision = '2b6fd9c6b493'
down_revision = '26d219dee350'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DataGroup', sa.Column('valid_pipelines', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DataGroup', 'valid_pipelines')
    ### end Alembic commands ###
