"""empty message

Revision ID: 4f19ac02204d
Revises: b9f1fa575c0c
Create Date: 2016-05-19 10:05:01.929346

"""

# revision identifiers, used by Alembic.
revision = '4f19ac02204d'
down_revision = 'b9f1fa575c0c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PipelineInstance', sa.Column('client_data_group_id', sa.Integer(), nullable=True))
    op.drop_constraint('PipelineInstance_ibfk_1', 'PipelineInstance', type_='foreignkey')
    op.create_foreign_key(None, 'PipelineInstance', 'DataGroup', ['client_data_group_id'], ['id'])
    op.drop_column('PipelineInstance', 'consignor_data_group_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PipelineInstance', sa.Column('consignor_data_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'PipelineInstance', type_='foreignkey')
    op.create_foreign_key('PipelineInstance_ibfk_1', 'PipelineInstance', 'DataGroup', ['consignor_data_group_id'], ['id'])
    op.drop_column('PipelineInstance', 'client_data_group_id')
    ### end Alembic commands ###
