"""empty message

Revision ID: 57f02a680ce2
Revises: None
Create Date: 2016-04-27 15:31:40.135042

"""

# revision identifiers, used by Alembic.
revision = '57f02a680ce2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['Group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('I', 'II', 'III'), nullable=False),
    sa.Column('regex_type', sa.Enum('AND', 'OR'), nullable=False),
    sa.Column('regex', sa.String(length=100), nullable=False),
    sa.Column('documentation', sa.String(length=50), nullable=False),
    sa.Column('executable', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key'),
    sa.UniqueConstraint('name', 'author', 'version', name='_unique')
    )
    op.create_table('ReferenceData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('current', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key'),
    sa.UniqueConstraint('name', 'path', 'description', 'version', name='_unique')
    )
    op.create_table('Person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('Member', 'Group Admin', 'Site Admin'), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('_password', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('PipelineModule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('executor', sa.String(length=500), nullable=False),
    sa.Column('execution_index', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['Pipeline.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key'),
    sa.UniqueConstraint('pipeline_id', 'execution_index', name='_unique')
    )
    op.create_table('Customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PipelineModuleOption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parameter_name', sa.String(length=50), nullable=False),
    sa.Column('user_interaction_type', sa.Enum('file', 'string', 'boolean', 'reference', 'enum'), nullable=False),
    sa.Column('default_value', sa.String(length=100), nullable=False),
    sa.Column('necessary', sa.SmallInteger(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['PipelineModule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DataGroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('updated_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key')
    )
    op.create_table('Project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('updated_date', sa.Date(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key')
    )
    op.create_table('DataGroupToCustomer',
    sa.Column('data_group_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.id'], ),
    sa.ForeignKeyConstraint(['data_group_id'], ['DataGroup.id'], )
    )
    op.create_table('Document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('updated_date', sa.Date(), nullable=True),
    sa.Column('project_identifier', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_identifier'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key')
    )
    op.create_table('PipelineInstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('current_execution_index', sa.Integer(), nullable=True),
    sa.Column('current_execution_status', sa.Enum('NOT_STARTED', 'WAITING', 'RUNNING', 'STOPPED', 'FINISHED', 'ERROR'), nullable=True),
    sa.Column('execution_type', sa.Enum('Per Module', 'Continuous'), nullable=True),
    sa.Column('options_type', sa.Enum('Custom', 'Default'), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('consignor_data_group_id', sa.Integer(), nullable=True),
    sa.Column('output_data_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consignor_data_group_id'], ['DataGroup.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.ForeignKeyConstraint(['output_data_group_id'], ['DataGroup.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['Pipeline.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key')
    )
    op.create_table('ProjectToCustomer',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], )
    )
    op.create_table('Submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('updated_date', sa.Date(), nullable=True),
    sa.Column('validated', sa.SmallInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('data_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_group_id'], ['DataGroup.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key')
    )
    op.create_table('PipelineModuleInstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_instance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['PipelineModule.id'], ),
    sa.ForeignKeyConstraint(['pipeline_instance_id'], ['PipelineInstance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key')
    )
    op.create_table('Sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('updated_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.ForeignKeyConstraint(['pipeline_source_id'], ['PipelineInstance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key')
    )
    op.create_table('DataItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('updated_date', sa.Date(), nullable=True),
    sa.Column('unlocalised_path', sa.String(length=100), nullable=False),
    sa.Column('data_group_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_group_id'], ['DataGroup.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['Sample.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key')
    )
    op.create_table('PipelineModuleOptionValue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_key', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('module_instance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_instance_id'], ['PipelineModuleInstance.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['PipelineModuleOption.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_key')
    )
    op.create_table('ProjectSampleGrouping',
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['Sample.id'], )
    )
    op.create_table('SampleToCustomer',
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['Sample.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SampleToCustomer')
    op.drop_table('ProjectSampleGrouping')
    op.drop_table('PipelineModuleOptionValue')
    op.drop_table('DataItem')
    op.drop_table('Sample')
    op.drop_table('PipelineModuleInstance')
    op.drop_table('Submission')
    op.drop_table('ProjectToCustomer')
    op.drop_table('PipelineInstance')
    op.drop_table('Document')
    op.drop_table('DataGroupToCustomer')
    op.drop_table('Project')
    op.drop_table('DataGroup')
    op.drop_table('User')
    op.drop_table('PipelineModuleOption')
    op.drop_table('Customer')
    op.drop_table('PipelineModule')
    op.drop_table('Person')
    op.drop_table('ReferenceData')
    op.drop_table('Pipeline')
    op.drop_table('Group')
    ### end Alembic commands ###
