"""empty message

Revision ID: 6bf741e1abe7
Revises: 0faa4a12640e
Create Date: 2016-04-20 15:57:15.154843

"""

# revision identifiers, used by Alembic.
revision = '6bf741e1abe7'
down_revision = '0faa4a12640e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'PipelineInstance', 'DataSource', ['data_consigner_id'], ['id'], use_alter=True)
    op.add_column('ReferenceData', sa.Column('path', sa.String(length=50), nullable=False))
    op.drop_constraint('_unique', 'ReferenceData', type_='unique')
    op.create_unique_constraint('_unique', 'ReferenceData', ['name', 'path', 'description', 'version'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_unique', 'ReferenceData', type_='unique')
    op.create_unique_constraint('_unique', 'ReferenceData', ['name', 'description', 'version'])
    op.drop_column('ReferenceData', 'path')
    op.drop_constraint(None, 'PipelineInstance', type_='foreignkey')
    ### end Alembic commands ###
