"""empty message

Revision ID: 86e41d66b10a
Revises: 57f02a680ce2
Create Date: 2016-04-28 15:52:39.295676

"""

# revision identifiers, used by Alembic.
revision = '86e41d66b10a'
down_revision = '57f02a680ce2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DataGroup', sa.Column('running', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DataGroup', 'running')
    ### end Alembic commands ###
