"""empty message

Revision ID: 9a2a8df1bda0
Revises: ea6764b46df4
Create Date: 2016-05-06 11:46:55.505295

"""

# revision identifiers, used by Alembic.
revision = '9a2a8df1bda0'
down_revision = 'ea6764b46df4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Group', sa.Column('_password', sa.String(length=160), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Group', '_password')
    ### end Alembic commands ###
