"""empty message

Revision ID: be8e13c91a30
Revises: 488abd944134
Create Date: 2016-04-07 09:49:35.970697

"""

# revision identifiers, used by Alembic.
revision = 'be8e13c91a30'
down_revision = '488abd944134'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'PipelineInstance', 'User', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'PipelineInstance', 'DataSource', ['data_consigner_id'], ['id'], use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PipelineInstance', type_='foreignkey')
    op.drop_constraint(None, 'PipelineInstance', type_='foreignkey')
    ### end Alembic commands ###
