"""empty message

Revision ID: e57d5b5489cc
Revises: 37ac45f92eb7
Create Date: 2016-04-29 14:48:34.056971

"""

# revision identifiers, used by Alembic.
revision = 'e57d5b5489cc'
down_revision = '37ac45f92eb7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PipelineInstance', sa.Column('pipeline_output_data_group_id', sa.Integer(), nullable=True))
    op.add_column('PipelineInstance', sa.Column('sample_output_data_group_id', sa.Integer(), nullable=True))
    op.drop_constraint('PipelineInstance_ibfk_3', 'PipelineInstance', type_='foreignkey')
    op.create_foreign_key(None, 'PipelineInstance', 'DataGroup', ['pipeline_output_data_group_id'], ['id'])
    op.create_foreign_key(None, 'PipelineInstance', 'DataGroup', ['sample_output_data_group_id'], ['id'])
    op.drop_column('PipelineInstance', 'output_data_group_id')
    op.add_column('PipelineModuleInstance', sa.Column('module_output_data_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'PipelineModuleInstance', 'DataGroup', ['module_output_data_group_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PipelineModuleInstance', type_='foreignkey')
    op.drop_column('PipelineModuleInstance', 'module_output_data_group_id')
    op.add_column('PipelineInstance', sa.Column('output_data_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'PipelineInstance', type_='foreignkey')
    op.drop_constraint(None, 'PipelineInstance', type_='foreignkey')
    op.create_foreign_key('PipelineInstance_ibfk_3', 'PipelineInstance', 'DataGroup', ['output_data_group_id'], ['id'])
    op.drop_column('PipelineInstance', 'sample_output_data_group_id')
    op.drop_column('PipelineInstance', 'pipeline_output_data_group_id')
    ### end Alembic commands ###
