"""empty message

Revision ID: f3f26923f6bc
Revises: be8e13c91a30
Create Date: 2016-04-14 10:45:18.092290

"""

# revision identifiers, used by Alembic.
revision = 'f3f26923f6bc'
down_revision = 'be8e13c91a30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'PipelineInstance', 'DataSource', ['data_consigner_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'PipelineInstance', 'User', ['user_id'], ['id'], use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PipelineInstance', type_='foreignkey')
    op.drop_constraint(None, 'PipelineInstance', type_='foreignkey')
    ### end Alembic commands ###
