#!/usr/bin/python
import cgi
import cgitb
import API.templateBuilder as writer

cgitb.enable()

from API.runObj2array import runObj2array
from API.seqRun import seqRun

writer.writeOutCGI()
writer.writeOutHeader()

csvFile = cgi.FieldStorage()

# Create a seqRun instance
i = []

i.append(seqRun())
i[-1].addSeqProject()
i[-1].seqProjs[0].addLaneData()
i[-1].seqProjs[0].lanes[0].addSamples()

# expArr=[]
# expArr.append(projs)
# d=runObj2array(expArr)
print \
    """<p>Enter the sequence run parameters.</p>"""

d = runObj2array(i)
# print "<p>",d,"</p>"
print \
    '<form id="form" name="newSeqRun" method="post" action="/cgi-bin/insertSeqRun">'
print \
    "<script src='/js/manualRunFormTable.js'></script>"
print \
    "<script>"
print \
    d
print \
    "experimentTable(runArr);"
print \
    "</script>"
print \
    '<input id="submit" type="submit" value="Insert">'
print \
    '</form>'

writer.writeOutFooter()
