#!/usr/bin/python


import cgi

link = cgi.FieldStorage()

CH = open("./cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("./template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("./template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

from API.runQuery import runQuery
from API.getRunByID import getRunByID

for ch in cgiHeader:
    print
    ch[:-1]
for he in topLines:
    print
    he[:-1]

id = link["runID"].value
# id="P211"

i = getRunByID(id)
# Get unlinked seq projects

DBquery = "select  seqProjectID, seqProjectName from seqProject where seqRunID=0"

res = runQuery(DBquery)

print
'<form id="linkst" name="entitiesToLink" method="post" action="/cgi-bin/coreInSys/makeSeqLinks?runID=' + id + '">'
print
'<input id="Linkbutton" type="submit" value="make links">'
print
"<table border=2>"

for rr in range(0, len(res)):
    try:
        print
        "<tr>"
        print
        "<td>" + str(res[rr][0]) + "</td>"
        print
        "<td>" + res[rr][1] + "</td>"
        print
        '<td><input type="checkbox" name="seq_' + str(res[rr][0]) + '" value="' + str(res[rr][0]) + '"></td>'
        print
        "</tr>"
    except:
        print
        "<tr><td>Illegal values in output.</td></tr>"

print
"</table>"

for fo in bottomLines:
    print
    fo[:-1]
