#!/usr/bin/python

import cgi

form=cgi.FieldStorage()
from API.masterProject import masterProject


CH=open("../template/cgi_header","r")
cgiHeader=CH.readlines()
CH.close()


HF=open("../template/template_top.html","r")
topLines=HF.readlines()
HF.close()

FF=open("../template/template_bottom.html","r")
bottomLines=FF.readlines()
FF.close()


from API.getAllProjects import getAllProjects


for ch in cgiHeader:
    print ch[:-1]

for he in topLines:
    print he[:-1]


if form.has_key("PROJ_NAME"):
    projectName=form["PROJ_NAME"].value
if form.has_key("PROJ_LEAD"):
    projectLead=form["PROJ_LEAD"].value

i=masterProject()
i.projectName=projectName
i.projectLead=projectLead
import datetime
today=datetime.date.today()
openDate=str(today.year)+"-"+str(today.month)+"-"+str(today.day)
i.openDate=openDate
#print "i.openDate",i.openDate

i.setLastUpdate()


i.insertMasterProject()
i.getLastMasterProjectID()

#projects=getAllProjects()

#print projects
#Get a list of all of the projects in the database:
#print "<p>",projects,"</p>"

print '
<table border="1" align="center" valign="top" cellpadding="0" cellspacing="0" width=100%>'
    print '
    <tr>
        <th>Project Name</th>
        <th>Run Name</th>
        <th>Project Type</th>
        <th>Customer ID</th>
        <th>Project Status</th>
    </tr>
    '

    """

    for pro in range(0,len(projects)):
    print '
    <tr>
        <td>
            <a href="/cgi-bin/getProjectFromDB?projName='+projects[pro][4]+'&projType='+projects[pro][2]+'&projID='+str(projects[pro][1])+'">
                '+projects[pro][4]+'</a></td>
        <td><a href="/cgi-bin/getSeqRunFromDB?projID='+projects[pro][6]+'"> '+projects[pro][6]+' </a></td>
        <td>'+projects[pro][2]+'</td>
        <td>'+str(projects[pro][7])+'</td>
        <td>'+projects[pro][3]+'</td>
    </tr>
    '


    """

    #send it back to the project page

    print '
    <script language="javascript" type="text/javascript">'
    print
    'window.location.href="/cgi-bin/getProjectFromDB.cgi?projID=' + i.masterProjectID + '";'
    print
    '</script>
    '


    for fo in bottomLines:
    print fo[:-1]




