#!/usr/bin/python
import cgi
import cgitb
import API.templateBuilder as writer

# Variable that can be used to test the script in an ide environment
debug = True
cgitb.enable()

writer.writeOutCGI()
writer.writeOutHeader()

form = cgi.FieldStorage()
if form.has_key("PROJ_NAME") and form.has_key("PROJ_LEAD"):
    pn = form["PROJ_NAME"].value
    pl = form["PROJ_LEAD"].value
    from API.sqlFormatter import stripIllegalSQLCharacters as formatter
    projectName = formatter(pn)
    projectLead = formatter(pl)

    from API.masterProject import masterProject
    i = masterProject()
    i.projectName = projectName
    i.projectLead = projectLead
    import datetime

    today = datetime.date.today()
    openDate = str(today.year) + "-" + str(today.month) + "-" + str(today.day)
    i.openDate = openDate
    # print "i.openDate",i.openDate

    i.setLastUpdate()

    i.insertMasterProject()
    i.getLastMasterProjectID()

    # projects=getAllProjects()
    # print projects
    # Get a list of all of the projects in the database:
    # print "<p>",projects,"</p>"
    print \
        '<table border="1" align="center" valign="top" cellpadding="0" cellspacing="0" width=100%>'
    print \
        '<tr><th>Project Name</th><th>Run Name</th><th>Project Type</th><th>Customer ID</th><th>Project Status</th></tr>'

    """
    for pro in range(0,len(projects)):
        print \
            '<tr><td><a href="/cgi-bin/getProjectFromDB?projName='+projects[pro][4]+'&projType='+projects[pro][2]+'&projID='+str(projects[pro][1])+'">'+projects[pro][4]+'</a></td><td><a href="/cgi-bin/getSeqRunFromDB?projID='+projects[pro][6]+'"> '+projects[pro][6]+' </a></td><td>'+projects[pro][2]+'</td><td>'+str(projects[pro][7])+'</td><td>'+projects[pro][3]+'</td></tr>'
    """

    # send it back to the project page
    print \
        '<script language="javascript" type="text/javascript">'
    print \
        'window.location.href="/cgi-bin/getProjectFromDB?projID=' + i.masterProjectID + '";'
    print \
        '</script>'

elif debug:
    projectName = "Jon Project"
    projectLead = "Jon"

    from API.masterProject import masterProject
    i = masterProject()
    i.projectName = projectName
    i.projectLead = projectLead
    import datetime

    today = datetime.date.today()
    openDate = str(today.year) + "-" + str(today.month) + "-" + str(today.day)
    i.openDate = openDate
    # print "i.openDate",i.openDate

    i.setLastUpdate()

    i.insertMasterProject()
    i.getLastMasterProjectID()

    # projects=getAllProjects()
    # print projects
    # Get a list of all of the projects in the database:
    # print "<p>",projects,"</p>"
    print \
        '<table border="1" align="center" valign="top" cellpadding="0" cellspacing="0" width=100%>'
    print \
        '<tr><th>Project Name</th><th>Run Name</th><th>Project Type</th><th>Customer ID</th><th>Project Status</th></tr>'

    """
    for pro in range(0,len(projects)):
        print \
            '<tr><td><a href="/cgi-bin/getProjectFromDB?projName='+projects[pro][4]+'&projType='+projects[pro][2]+'&projID='+str(projects[pro][1])+'">'+projects[pro][4]+'</a></td><td><a href="/cgi-bin/getSeqRunFromDB?projID='+projects[pro][6]+'"> '+projects[pro][6]+' </a></td><td>'+projects[pro][2]+'</td><td>'+str(projects[pro][7])+'</td><td>'+projects[pro][3]+'</td></tr>'
    """

    # send it back to the project page
    print \
        '<script language="javascript" type="text/javascript">'
    print \
        'window.location.href="/cgi-bin/getProjectFromDB?projID=' + i.masterProjectID + '";'
    print \
        '</script>'

else:
    print \
        '<p>Information entered was not complete</p>'

writer.writeOutFooter()
