#!/usr/bin/python
__author__ = 'jon, alan'

import cgitb
import API.templateBuilder as writer

from API.projects import get_all

# Enable error tracing
cgitb.enable()

# Build the headers
writer.writeOutCGI()
writer.writeOutHeader()

# Return the projects
projects2 = get_all()

# Get a list of all of the projects in the database:
print \
    '               <table  id="projectstable" border="1" align="center" valign="top" cellpadding="0" cellspacing="0" width=100%>'
print \
    '                   <tr><th>Project ID</th><th>Project Name</th><th>Project Lead</th><th>Customer/Collaborator</th><th>Project opened</th><th>Project last updated</th><th>Project Status</th></tr>'

print \
    '                   <script src="/js/tableBuilder.js"></script>'

print \
    "                   <script>buildProjectsTable('" + projects2 + "');</script>"

print \
    '               </table>'

# Write out the footer
writer.writeOutFooter()
