#!/usr/bin/python

import cgi
link = cgi.FieldStorage()




CH=open("./cgi_header","r")
cgiHeader=CH.readlines()
CH.close()


HF=open("./template_top","r")
topLines=HF.readlines()
HF.close()

FF=open("./template_bottom","r")
bottomLines=FF.readlines()
FF.close()

from API.seqRun import seqRun


for ch in cgiHeader:
        print ch[:-1]

for he in topLines:
	print he[:-1]



laneID=link["laneID"].value

i=seqRun()
i.addSeqProject()
i.seqProjs[0].addLaneData()
#i.seqProjs[0].lanes[0].addSamples()
i.seqProjs[0].lanes[0].getLaneDataByID(laneID)
i.seqProjs[0].lanes[0].deleteLaneTree()




print "<p>Lane deleted</p>"






for fo in bottomLines:
	print fo[:-1]




