#!/usr/bin/python


import cgi

form = cgi.FieldStorage()

CH = open("./cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("./template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("./template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

from API.masterProject import masterProject
from API.runQuery import runQuery

for ch in cgiHeader:
    print
    ch[:-1]
for he in topLines:
    print
    he[:-1]

from API.runQuery import runQuery

masterProjectID = ""
if form.has_key("masterProjID"):
    masterProjectID = form["masterProjID"].value
projectName = ""
if form.has_key("projName"):
    projectName = form["projName"].value

seqLinks = []
analLinks = []
flowCytLinks = []

for t in form.keys():
    # print "<p>",t,form[t].value,"</p>"

    m = form[t].value

    bits = m.split("_")
    if bits[0] == "seq":
        DBquery = "delete from typeLinker where parentID=" + masterProjectID + " and childID=" + bits[1]
        # DBquery="insert into typeLinker (parentID, childID, type) values ('"+bits[2]+"','"+bits[1]+"','sequencing')"
        res = runQuery(DBquery)

print
'<script language="javascript" type="text/javascript">'
print
'window.location.href="/cgi-bin/coreInSys/getProjectFromDB.cgi?projID=' + masterProjectID + '&backurl="+window.location.href;'
print
'</script>'

for fo in bottomLines:
    print
    fo[:-1]
