#!/usr/bin/python



CH=open("./cgi_header","r")
cgiHeader=CH.readlines()
CH.close()


HF=open("./template_top","r")
topLines=HF.readlines()
HF.close()

FF=open("./template_bottom","r")
bottomLines=FF.readlines()
FF.close()


from API.getAllSeqRuns import getAllSeqRuns


for ch in cgiHeader:
        print ch[:-1]

for he in topLines:
	print he[:-1]


experiments=getAllSeqRuns()


#print "<p>",experiments,"</p>"

#Get a list of all of the projects in the database:
print '<table  border="1" align="center" valign="top" cellpadding="0" cellspacing="0" width=100%>'
print '<tr><th>Run Name</th><th>Start Date</th><th>End Date</th><th>Sequencing Project Name</th><th>Master Project Name</th></tr>'

for exp in range(0,len(experiments)):
	for pro in range(0,len(experiments[exp])):
		print '<tr><td><a href="/cgi-bin/coreInSys/getSeqRunFromDB.cgi?projID='+str(experiments[exp][pro][0])+'"> '+str(experiments[exp][pro][3])+' </a></td><td>'+str(experiments[exp][pro][1])+'</td><td>'+str(experiments[exp][pro][2])+'</td><td>'+str(experiments[exp][pro][4])+'</td><td><a href="/cgi-bin/coreInSys/getProjectFromDB.cgi?projName='+str(experiments[exp][pro][6])+'&projID='+str(experiments[exp][pro][5])+'">'+str(experiments[exp][pro][6])+'</a></td></tr>'

print '</table>'



for fo in bottomLines:
	print fo[:-1]




