#!/usr/bin/python
__author__ = "alan, jon"

import API.templateBuilder as writer

writer.writeOutCGI()
writer.writeOutHeader()

# Return the sequencing runs
from API.sequencing_summary import get_all
experiments = get_all()

# Get a list of all of the projects in the database:
print \
    '               <table id="sequencerunstable" border="1" align="center" valign="top" cellpadding="0" cellspacing="0" width=100%>'
print \
    '                   <tr><th>Run Name</th><th>Start Date</th><th>End Date</th><th>Sequencing Project Name</th><th>Master Project Name</th></tr>'
print \
    '                   <script src="/js/tableBuilder.js"></script>'
print \
    "                   <script>buildSequenceRunsTable('" + experiments + "');</script>"
print \
    '               </table>'

writer.writeOutFooter()
