#!/usr/bin/python

import cgi

link = cgi.FieldStorage()

CH = open("./cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("./template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("./template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

for ch in cgiHeader:
    print
    ch[:-1]

for he in topLines:
    print
    he[:-1]

from PL_CONTROL.sftpTransfer import sftpTransfer

ST = sftpTransfer()
if link.has_key('seqProjectID'):
    ST.seqProjectID = int(link['seqProjectID'].value)

if link.has_key('username'):
    ST.username = link['username'].value


# print "<p>"+str(ST.seqProjectID)+"</p><p>"+ST.username+"</p><p>"+ST.transLocation+"</p>"

ST.loadSftpByUsername()
ST.delSftpAccount()

print
'<script language="javascript" type="text/javascript">'
print
'window.location.href="/cgi-bin/coreInSys/seqProjDetails?projID=' + str(ST.seqProjectID) + '";'
print
'</script>'

# print '<p><a href="/cgi-bin/coreInSys/seqProjDetails?projID='+str(ST.seqProjectID)+'">Return to sequence project details page.</a></p>'

for fo in bottomLines:
    print
    fo[:-1]
