#!/usr/bin/python

import cgi

link = cgi.FieldStorage()

CH = open("./cgi_header", "r")
cgiHeader = CH.readlines()
CH.close()

HF = open("./template_top.html", "r")
topLines = HF.readlines()
HF.close()

FF = open("./template_bottom.html", "r")
bottomLines = FF.readlines()
FF.close()

for ch in cgiHeader:
    print
    ch[:-1]

for he in topLines:
    print
    he[:-1]

from PL_CONTROL.sftpTransfer import sftpTransfer

ST = sftpTransfer()
if link.has_key('seqProjectID'):
    ST.seqProjectID = int(link['seqProjectID'].value)

ST.genUsername()
ST.setTransLocation()

print
'<form method="post" action="/cgi-bin/coreInSys/sftpSetup2?seqProjectID=' + str(ST.seqProjectID) + '">'
print
'<table border=0 >'
print
'<tr><td>Username</td><td><input type="text" name="username" value="' + ST.username + '" size="80"></td></tr>'
print
'<tr><td>location on sftp server</td><td><input type="text" name="location" value="' + str(
    ST.transLocation) + '" size="80"></td></tr>'
print
'<tr><td>Contact email</td><td><input type="text" name="userContact" value="' + ST.userContact + '" size="80"></td></tr>'

print
"</table>"
print
'<input type="submit" value="Submit">'
print
'</form>'

for fo in bottomLines:
    print
    fo[:-1]
